export const orders = [
    { "product": "Laptop #1", "seller": "Seller #1", "country": "BRA", "price": 1000 },
    { "product": "Laptop #2", "seller": "Seller #2", "country": "ARG", "price": 1250 },
    { "product": "Laptop #3", "seller": "Seller #3", "country": "ARG", "price": 1900 },
    { "product": "Printer #1", "seller": "Seller #1", "country": "MEX", "price": 199 },
    { "product": "Smartphone #1", "seller": "Seller #2", "country": "BRA", "price": 999 },
    { "product": "Printer #2", "seller": "Seller #3", "country": "BRA", "price": 399 },
    { "product": "Smartphone #2", "seller": "Seller #1", "country": "ARG", "price": 1499 },
    { "product": "Laptop #3", "seller": "Seller #2", "country": "ARG", "price": 1900 },
    { "product": "Smartphone #1", "seller": "Seller #3", "country": "MEX", "price": 999 },
    { "product": "Printer #2", "seller": "Seller #1", "country": "BRA", "price": 399 },
    { "product": "Printer #3", "seller": "Seller #2", "country": "ARG", "price": 899 },
    { "product": "Laptop #2", "seller": "Seller #3", "country": "MEX", "price": 1250 },
    { "product": "Smartphone #1", "seller": "Seller #1", "country": "BRA", "price": 999 },
    { "product": "Printer #1", "seller": "Seller #2", "country": "BRA", "price": 199 },
    { "product": "Smartphone #3", "seller": "Seller #3", "country": "ARG", "price": 2399 },
    { "product": "Laptop #3", "seller": "Seller #1", "country": "MEX", "price": 1900 },
    { "product": "Smartphone #1", "seller": "Seller #2", "country": "BRA", "price": 999 },
    { "product": "Laptop #3", "seller": "Seller #3", "country": "BRA", "price": 1900 },
    { "product": "Smartphone #3", "seller": "Seller #1", "country": "BRA", "price": 2399 },
    { "product": "Printer #1", "seller": "Seller #2", "country": "ARG", "price": 199 },
    { "product": "Smartphone #2", "seller": "Seller #3", "country": "MEX", "price": 1499 },
    { "product": "Laptop #3", "seller": "Seller #1", "country": "ARG", "price": 1900 },
    { "product": "Printer #1", "seller": "Seller #2", "country": "MEX", "price": 199 },
    { "product": "Smartphone #3", "seller": "Seller #3", "country": "BRA", "price": 2399 },
    { "product": "Laptop #3", "seller": "Seller #1", "country": "BRA", "price": 1900 }
  ];